name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'current'
          cache: 'npm'
      - run: npm install
      - run: CI=false npm run build

      - uses: appleboy/ssh-action@v0.1.4
        with:
          username: root
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          script: docker compose -f /root/Judge0/docker-compose.yml down
      
      - uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          ARGS: "-avzr --delete"
          SOURCE: build/
          REMOTE_USER: root
          TARGET: /root/Judge0/ide

      - uses: appleboy/ssh-action@v0.1.4
        with:
          username: root
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          script: docker compose -f /root/Judge0/docker-compose.yml up -d